name: Run Cerberus Tests

on:
  push:
    branches:
      - master

permissions:
      contents: read
      actions: write
      
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tests in Cerberus Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: spring-media/ds_cerberus_playwright
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-tests